// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:                   string;
  type:                 FeatureType;
  place_type:           PlaceType[];
  relevance:            number;
  properties:           Properties;
  text_es:              string;
  language_es:          Language;
  place_name_es:        string;
  text:                 string;
  language:             Language;
  place_name:           string;
  bbox?:                number[];
  center:               number[];
  geometry:             Geometry;
  context:              Context[];
  matching_text?:       string;
  matching_place_name?: string;
}

export interface Context {
  id:           string;
  mapbox_id:    string;
  text_es:      string;
  text:         string;
  wikidata?:    string;
  language_es?: Language;
  language?:    Language;
  short_code?:  Language;
}

export enum Language {
  Es = "es",
  EsM = "ES-M",
}

export interface Geometry {
  type:        GeometryType;
  coordinates: number[];
}

export enum GeometryType {
  Point = "Point",
}

export enum PlaceType {
  Neighborhood = "neighborhood",
  Poi = "poi",
}

export interface Properties {
  mapbox_id?:  string;
  wikidata?:   string;
  category?:   string;
  landmark?:   boolean;
  address?:    string;
  foursquare?: string;
}

export enum FeatureType {
  Feature = "Feature",
}
